### ISSUE TITLE
Add Dutch language version

### ISSUE THREAD

**Issue by szeestraten** [szeestraten/final-countdown#27]
Use: https://github.com/kazupon/vue-i18n

Example: https://github.com/kazupon/vue-i18n/tree/dev/examples/ssr/src

**Comment by szeestraten** [comment]
@olizee Could you add dutch translations of the following texts?

      appFooterVueText: 'Created with',
      appFooterVueLink: 'https://vuejs.org',
      appFooterProjectLink: 'https://github.com/szeestraten',
      appFooterProjectText: 'by',

      homeTitleText: 'Tired of long meetings?',
      homeLeadText: 'Time management can be hard, especially during meetings. <br>Keep your meetings efficient with a timer.',
      homeLeadButton: 'Set a timer'

      timerTitleText: 'Set a timer',
      timerButtonText: {
        start: 'Start',
        pause: 'Pause',
        resume: 'Resume',
        reset: 'Reset',
      },

**Comment by olizee** [comment]
Check the reddish😊

Hartelijke groet,

Olivier Zeestraten
Business Coach

Ik help ondernemers bij het klaarstomen van hun business om door te kunnen groeien naar de volgende fase.

mobiel 06-14869776 | werkenaanjebedrijf.nl<http://www.olivierzeestraten.nl/>

[View-my-LinkedIn-profile-from-The-Linked-In-Man]<https://nl.linkedin.com/in/olivierzeestraten>

Van: Sandor Zeestraten [mailto:notifications@github.com]
Verzonden: zondag 11 juni 2017 15:47
Aan: szeestraten/final-countdown <final-countdown@noreply.github.com>
CC: olizee <ozeestraten@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [szeestraten/final-countdown] Add Dutch language version (#27)


@olizee<https://github.com/olizee> Could you add dutch translations of the following texts?

  appFooterVueText: 'Created with',

  appFooterVueLink: 'https://vuejs.org',

  appFooterProjectLink: 'https://github.com/szeestraten',

  appFooterProjectText: 'by',



  homeTitleText: 'Tired of long meetings?', ‘Ook helemaal klaar met rommelige, langdradige meetings?’

  homeLeadText: 'Time management can be hard, especially during meetings. ‘Time management in vergaderingen is vaak lastig. <br>Keep your meetings efficient with a timer.', Hou je meetings in de tang met een timer!

  homeLeadButton: 'Set a timer' Stel een timer in.



  timerTitleText: 'Set a timer',

  timerButtonText: {

    start: 'Start',

    pause: 'Pause',

    resume: 'Resume',

    reset: 'Reset',

  },

**Comment by szeestraten** [comment]
@olizee I've deployed an initial version with dutch localization. Give it a spin. All the dutch text is here if you want to edit it: https://github.com/szeestraten/final-countdown/blob/master/src/i18n/nl-NL.json

I still need to add some kind of cookie or technique to identify and remember which language has been selected. Tracking that in #32

**Comment by olizee** [comment]
Nice!

Hartelijke groet,

Olivier Zeestraten
Business Coach

Ik help ondernemers bij het klaarstomen van hun business om door te kunnen groeien naar de volgende fase.

mobiel 06-14869776 | werkenaanjebedrijf.nl<http://www.olivierzeestraten.nl/>

[View-my-LinkedIn-profile-from-The-Linked-In-Man]<https://nl.linkedin.com/in/olivierzeestraten>

Van: Sandor Zeestraten [mailto:notifications@github.com]
Verzonden: donderdag 15 juni 2017 22:40
Aan: szeestraten/final-countdown <final-countdown@noreply.github.com>
CC: olizee <ozeestraten@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [szeestraten/final-countdown] Add Dutch language version (#27)


Closed #27<https://github.com/szeestraten/final-countdown/issues/27>.
