### ISSUE TITLE
Add alarm sound

### ISSUE THREAD

**Issue by szeestraten** [szeestraten/final-countdown#5]
Calm meditiation bell suggest by Olivier.

**Comment by szeestraten** [comment]
Going with this one: http://freesound.org/people/Daphne_in_Wonderland/sounds/127167/

**Comment by szeestraten** [comment]
@olizee, meditation bell has been added. Please check if it works and if the volume is OK.

**Comment by olizee** [comment]
Works like a charm!

Hartelijke groet,

Olivier Zeestraten
Business Coach

Ik help ondernemers bij het klaarstomen van hun business om door te kunnen groeien naar de volgende fase.

mobiel 06-14869776 | werkenaanjebedrijf.nl<http://www.olivierzeestraten.nl/>

[View-my-LinkedIn-profile-from-The-Linked-In-Man]<https://nl.linkedin.com/in/olivierzeestraten>

Van: Sandor Zeestraten [mailto:notifications@github.com]
Verzonden: zondag 11 juni 2017 13:43
Aan: szeestraten/final-countdown <final-countdown@noreply.github.com>
CC: olizee <ozeestraten@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [szeestraten/final-countdown] Add alarm sound (#5)


@olizee<https://github.com/olizee>, meditation bell has been added. Please check if it works and if the volume is OK.
